
CREATE TYPE AMPLITUDE_TYPE AS TABLE ("AMPLITUDE" double);

CREATE PROCEDURE SELECT_START_OF_SIGNAL(IN SIG_NAME VARCHAR(10), IN REC_ID,IN SIG_LEN, OUT OUTPUT_TABLE AMPLITUDE_TYPE)
LANGUAGE SQLSCRIPT AS
BEGIN
	DECLARE START_POINT INT :=0;
	query_string = 'SELECT MIN(SAMPLE_ID) INTO START_POINT FROM "MIMIC2V26"."wav_num_sig_' || :SIG_NAME || '"
	WHERE "MIMIC2V26"."wav_num_sig_' || :SIG_NAME || '".AMPLITUDE">0';
	
	EXEC query_string;
	query_string = 'OUTPUT_TABLE = SELECT AMPLITUDE FROM "MIMIC2V26"."wav_num_sig_' || :SIG_NAME || '"
	WHERE "MIMIC2V26"."wav_num_sig_' || :SIG_NAME || '".SAMPLE_ID"> :START_POINT 
	AND "MIMIC2V26"."wav_num_sig_' || :SIG_NAME || '".SAMPLE_ID"< :START_POINT + :SIG_LEN';
END


	
	
	
			
	