SELECT * FROM (SELECT "CAF"."ICUSTAY_ID",
    "CAF"."SUBJECT_ID",
    CASE
      WHEN ( "CAF"."AKI1_ICU48" = 1)
      THEN 1
      WHEN ( "CAF"."AKI2_ICU48" =1)
      THEN 2
      WHEN ( "CAF"."AKI3_ICU48" =1)
      THEN 3
      ELSE 0
    END AS "AKI_CATEGORY_ICU48",
    
    CASE
      WHEN ( "CAF"."AKI1_ICU48_VS_HOSP" = 1)
      THEN 1
      WHEN ( "CAF"."AKI2_ICU48_VS_HOSP" =1)
      THEN 2
      WHEN ( "CAF"."AKI3_ICU48_VS_HOSP" =1)
      THEN 3
      ELSE 0
    END AS "AKI_CATEGORY_ICU48_VS_HOSP",
    
    CASE
      WHEN ( "CAF"."AKI1_ICU_VS_HOSP" = 1)
      THEN 1
      WHEN ( "CAF"."AKI2_ICU_VS_HOSP" = 1)
      THEN 2
      WHEN ( "CAF"."AKI3_ICU_VS_HOSP" = 1)
      THEN 3
      ELSE 0
    END AS "AKI_CATEGORY_ICU_VS_HOSP"
    
  FROM (SELECT "SUBJECT_ID",
    "ICUSTAY_ID",
    "HOSPITAL_ADMIT_AGE",
    "HOSPITAL_AGE_GROUP",
    "FIRST_CR",
    "MAX_CR_PER_ICUSTAY",
    "MAX_INCREASE",
    "MAX_PERCENT_INCREASE",
  
    -- IN THE FIRST 48 HOURS OF ICU
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND (("MAX_CR_INCREASE_ICU_48"     >= 0.3
       AND   "MAX_CR_INCR_ICU_48_PERC"    < 200 )
      OR  (  "MAX_CR_INCR_ICU_48_PERC"    >= 150
      AND    "MAX_CR_INCR_ICU_48_PERC"    < 200) ) )
      THEN 1
      ELSE 0
    END AS "AKI1_ICU48",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND   "MAX_CR_INCR_ICU_48_PERC"    < 300
       AND   "MAX_CR_INCR_ICU_48_PERC"    >= 200 )
      THEN 1
      ELSE 0
    END AS "AKI2_ICU48",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           >= 4
      OR "MAX_CR_INCR_ICU_48_PERC" >= 300 )
      THEN 1
      ELSE 0
    END AS "AKI3_ICU48",
   
   
    -- MAX CR IN 48 HRS OF ICU VS MIN IN HOSPITAL STAY
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND (("MAX_CR_INCR_ICU_48_VS_HOS"     >= 0.3
       AND   "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    < 200 )
      OR  (  "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    >= 150
      AND    "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    < 200) ) )
      THEN 1
      ELSE 0
    END AS "AKI1_ICU48_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND   "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    < 300
       AND   "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    >= 200 )
      THEN 1
      ELSE 0
    END AS "AKI2_ICU48_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           >= 4
      OR "MAX_CR_INCR_ICU_48_VS_HOS_PERC" >= 300 )
      THEN 1
      ELSE 0
    END AS "AKI3_ICU48_VS_HOSP", 
    
    
    CASE
      WHEN ( "MAX_CR_PER_ICUSTAY"           < 4
       AND (("MAX_CR_INCR_ICU_VS_HOS"     >= 0.3
       AND   "MAX_CR_INCR_ICU_VS_HOS_PERC"    < 200 )
      OR  (  "MAX_CR_INCR_ICU_VS_HOS_PERC"    >= 150
      AND    "MAX_CR_INCR_ICU_VS_HOS_PERC"    < 200) ) )
      THEN 1
      ELSE 0
    END AS "AKI1_ICU_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_PER_ICUSTAY"           < 4
       AND   "MAX_CR_INCR_ICU_VS_HOS_PERC"    < 300
       AND   "MAX_CR_INCR_ICU_VS_HOS_PERC"    >= 200 )
      THEN 1
      ELSE 0
    END AS "AKI2_ICU_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_PER_ICUSTAY"           >= 4
      OR "MAX_CR_INCR_ICU_VS_HOS_PERC" >= 300 )
      THEN 1
      ELSE 0
    END AS "AKI3_ICU_VS_HOSP"
      
    
  FROM ( SELECT DISTINCT "CV"."SUBJECT_ID",
    "CV"."ICUSTAY_ID",
    "CV"."HOSPITAL_AGE_GROUP",
    "CV"."HOSPITAL_ADMIT_AGE",
    MAX("CV"."MAX_INCREASE") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR")                                                 "MAX_INCREASE",
    FIRST_VALUE("CV"."LONG_CHARTTIME") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR" ORDER BY "CV"."MAX_INCREASE" DESC)         "DATE_MAX_INCREASE",
    MAX("CV"."PERCENTAGE_INCREASE") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR")                                          "MAX_PERCENT_INCREASE",
    FIRST_VALUE("CV"."LONG_CHARTTIME") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR" ORDER BY "CV"."PERCENTAGE_INCREASE" DESC)  "DATE_MAX_PERCENT_INCREASE",
    
    "FCR"."FIRST_CR",
    
    "CR"."MAX_CR" AS    "MAX_CR_PER_ICUSTAY",
    "MICR"."MIN_CR" AS  "MIN_CR_PER_ICUSTAY",

    "MCPHS"."MIN_CR_PER_HOSP_ADM",
    "MACPHS"."MAX_CR_PER_HOSP_ADM",
    
    -- THE 48 HR VALUES
    "MCIHR"."MAX_CR_48" AS        "MAX_CR_ICU_48HRS",
    "MICI48"."MIN_CR_48" AS       "MIN_CR_ICU_48HRS",
    
    "MICRHS"."MIN_CR_PER_HOSP_ADM_48",
    "MACRHS"."MAX_CR_PER_HOSP_ADM_48",
    
    --MAX CREATININ INCREASE IN ICU FOR ONLY FIRST 48 HOURS
    ("MCIHR"."MAX_CR_48" - "MICI48"."MIN_CR_48")                                                    AS "MAX_CR_INCREASE_ICU_48",
    100*("MCIHR"."MAX_CR_48" - "MICI48"."MIN_CR_48") / "MICI48"."MIN_CR_48"                                 AS "MAX_CR_INCR_ICU_48_PERC",
    
    --MAX CREATININ INCREASE IN FIRST 48 HOURS ICU VERSUS MIN OF HOSPITAL STAY
    ("MCIHR"."MAX_CR_48" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                           AS "MAX_CR_INCR_ICU_48_VS_HOS",
    100*("MCIHR"."MAX_CR_48" - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"               AS "MAX_CR_INCR_ICU_48_VS_HOS_PERC",
    
    -- MAX CREATININ INCREASE IN TOTAL ICU STAY VERSUS MIN IN THE HOSPITAL                  
    ("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                                 AS "MAX_CR_INCR_ICU_VS_HOS",          
    100*("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"                     AS "MAX_CR_INCR_ICU_VS_HOS_PERC",      
    
    
    "FCR"."FIRST_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM" AS       "BL_CR_INCREASE",           -- DIFFERENCE BETWEEN CR ADMISSION AND MINIMUM VALUE OVER HOSPITAL STAY 
    "FCR"."FIRST_CR" * 100 / "MCPHS"."MIN_CR_PER_HOSP_ADM" AS "BL_CR_PERCENT_INCREASE"    -- % VALUE OF ABOVE
  FROM ( SELECT DISTINCT "CR"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    "ICUD"."ICUSTAY_AGE_GROUP" AS "HOSPITAL_AGE_GROUP",
    "ICUD"."ICUSTAY_ADMIT_AGE" AS "HOSPITAL_ADMIT_AGE",
    "ICUD"."ICUSTAY_INTIME",
    "ICUD"."ICUSTAY_OUTTIME",
    "CR"."CHARTTIME",
    TO_CHAR("CR"."CHARTTIME", 'DD MON, YYYY HH24:MI:SS')                                                                                                             AS "LONG_CHARTTIME",
    "CR"."VALUENUM"                                                                                                                                                  AS "CURRENT_CR",
    MAX("CR"."VALUENUM") OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME")                        AS "MAX_CR_NEXT_TWO_DAY",
    MAX("CR"."VALUENUM") OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME")    - "CR"."VALUENUM"       AS "MAX_INCREASE",
    (MAX("CR"."VALUENUM") OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME") ) * 100 / "CR"."VALUENUM" AS "PERCENTAGE_INCREASE"
  FROM "MIMIC2V26"."labevents" "CR",
    "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "ICUD"."ICUSTAY_ID" = "CR"."ICUSTAY_ID"
  AND "CR"."ITEMID"         = 50090
  AND "CR"."VALUENUM"      <> 0
    /* ELIMINATE '0'S TO PREVENT DIVIDE BY ZERO ERROR */
  AND "CR"."VALUENUM" IS NOT NULL
  ORDER BY "CR"."SUBJECT_ID",
    "CR"."CHARTTIME"
  ) "CV"
  
  JOIN (SELECT "ICUD"."ICUSTAY_ID",
    MAX("CR"."VALUENUM") AS "MAX_CR"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  GROUP BY "ICUD"."ICUSTAY_ID"
  )            "CR"
  ON ( "CV"."ICUSTAY_ID" = "CR"."ICUSTAY_ID" )
  JOIN (SELECT "ICUD"."ICUSTAY_ID",
    MIN("CR"."VALUENUM") AS "MIN_CR"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  GROUP BY "ICUD"."ICUSTAY_ID"
  )            "MICR"
  ON ( "CV"."ICUSTAY_ID" = "MICR"."ICUSTAY_ID")
  
  JOIN ( SELECT DISTINCT "ICUD"."ICUSTAY_ID",
    FIRST_VALUE ( "CR"."VALUENUM" ) OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME" ) "FIRST_CR"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  )          "FCR"
  ON ( "CV"."ICUSTAY_ID" = "FCR"."ICUSTAY_ID" )
  
  
  LEFT JOIN ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MIN("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MIN_CR_PER_HOSP_ADM"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID"
  FROM "MIMIC2V26"."icustay_detail" "ICUD"
  JOIN "MIMIC2V26"."procedureevents" "P"
  ON "ICUD"."HADM_ID"="P"."HADM_ID"
  AND "P"."ITEMID"  IN (60887,60491,100586,100622,100977,100991)
  ORDER BY "ICUD"."SUBJECT_ID"
  )
    )
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )          "MCPHS"
  ON ( "CV"."ICUSTAY_ID" = "MCPHS"."ICUSTAY_ID" )
  
  --THE 48 HOUR PART
  LEFT JOIN ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MAX("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MAX_CR_PER_HOSP_ADM"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID"
  FROM "MIMIC2V26"."icustay_detail" "ICUD"
  JOIN "MIMIC2V26"."procedureevents" "P"
  ON "ICUD"."HADM_ID"="P"."HADM_ID"
  AND "P"."ITEMID"  IN (60887,60491,100586,100622,100977,100991)
  ORDER BY "ICUD"."SUBJECT_ID"
  )
    )
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )          "MACPHS"
  ON ( "CV"."ICUSTAY_ID" = "MACPHS"."ICUSTAY_ID" ) 
  
  JOIN (SELECT "ICUD"."ICUSTAY_ID",
    MAX("CR"."VALUENUM") AS "MAX_CR_48"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME",2) >  "CR"."CHARTTIME" 
  GROUP BY "ICUD"."ICUSTAY_ID"
  )              "MCIHR"
  ON ( "CV"."ICUSTAY_ID" = "MCIHR"."ICUSTAY_ID") 
  JOIN (SELECT "ICUD"."ICUSTAY_ID",
    MIN("CR"."VALUENUM") AS "MIN_CR_48"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME", 2) >  "CR"."CHARTTIME" 
  GROUP BY "ICUD"."ICUSTAY_ID"
  )              "MICI48"
  ON ( "CV"."ICUSTAY_ID" = "MICI48"."ICUSTAY_ID" ) 
  
  JOIN ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MIN("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MIN_CR_PER_HOSP_ADM_48"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID"
  FROM "MIMIC2V26"."icustay_detail" "ICUD"
  JOIN "MIMIC2V26"."procedureevents" "P"
  ON "ICUD"."HADM_ID"="P"."HADM_ID"
  AND "P"."ITEMID"  IN (60887,60491,100586,100622,100977,100991)
  ORDER BY "ICUD"."SUBJECT_ID"
  )
    )
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME", 2) >  "LE"."CHARTTIME"     
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )                "MICRHS"
  ON ( "CV"."ICUSTAY_ID" = "MICRHS"."ICUSTAY_ID" ) 
  JOIN ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MAX("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MAX_CR_PER_HOSP_ADM_48"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID"
  FROM "MIMIC2V26"."icustay_detail" "ICUD"
  JOIN "MIMIC2V26"."procedureevents" "P"
  ON "ICUD"."HADM_ID"="P"."HADM_ID"
  AND "P"."ITEMID"  IN (60887,60491,100586,100622,100977,100991)
  ORDER BY "ICUD"."SUBJECT_ID"
  )
    )
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME", 2) >  "LE"."CHARTTIME"   
    
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )                "MACRHS"
  ON ( "CV"."ICUSTAY_ID" = "MACRHS"."ICUSTAY_ID" ) 
  
  WHERE "MICR"."MIN_CR" > 0
  AND "MCPHS"."MIN_CR_PER_HOSP_ADM" > 0
  AND "MICI48"."MIN_CR_48" > 0
  AND "MICRHS"."MIN_CR_PER_HOSP_ADM_48" > 0
  
  )
  ) "CAF"
  );


