WITH 
/* A PATIENTS MAXUMIM CREATININE VALUE DURING AN ICU STAY */
  
  -- THE FIRST VALUE OF CREATININ PER ICUSTAY
  "FIRST_CREATININE_PER_ICU_STAY" AS
  ( SELECT DISTINCT "ICUD"."ICUSTAY_ID",
    FIRST_VALUE ( "CR"."VALUENUM" ) OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME" ) "FIRST_CR"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  )
  --SELECT COUNT(*) FROM FIRST_CREATININE_PER_ICU_STAY; 
  --THOSE ICUSTAY  THAT HAD A CREATININE MEASUREMENT = 30378
  
    /* PATIENTS WHO HAVE DIALYSIS DURING THEIR HOSPITAL ADMISSION */
  ,"RRT" AS
  ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID"
  FROM "MIMIC2V26"."icustay_detail" "ICUD"
  JOIN "MIMIC2V26"."procedureevents" "P"
  ON "ICUD"."HADM_ID"="P"."HADM_ID"
  AND "P"."ITEMID"  IN (60887,60491,100586,100622,100977,100991)
  ORDER BY "ICUD"."SUBJECT_ID"
  )
  --SELECT COUNT( DISTINCT SUBJECT_ID) FROM RRT;
  -- THOSE THAT HAD RRT = 1843
  
  -- THE MAXIMUM VALUE OF CREATININE PER ICU STAY
  ,"MAX_CREATININE_PER_ICU_STAY" AS
  (SELECT "ICUD"."ICUSTAY_ID",
    MAX("CR"."VALUENUM") AS "MAX_CR"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  GROUP BY "ICUD"."ICUSTAY_ID"
  )
  --SELECT COUNT(DISTINCT *) FROM MAX_CREATININE_PER_ICU_STAY;
  
  
  -- THE MINIMUM VALUE OF CREATININE PER ICUSTAY
  ,"MIN_CREATININE_PER_ICU_STAY" AS
  (SELECT "ICUD"."ICUSTAY_ID",
    MIN("CR"."VALUENUM") AS "MIN_CR"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  GROUP BY "ICUD"."ICUSTAY_ID"
  ) 

  -- THE MAXIMUM VALUE OF CREATININ BASED ON FIRST 48 HOURS IN THE ICU
  ,"MAX_CREAT_IN_ICU_48_HOURS" AS
  (SELECT "ICUD"."ICUSTAY_ID",
    MAX("CR"."VALUENUM") AS "MAX_CR_48"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME",2) >  "CR"."CHARTTIME" 
  GROUP BY "ICUD"."ICUSTAY_ID"
  )
  --SELECT * FROM MAX_CREAT_IN_ICU_48_HOURS;

  -- THE MINIMUM VALUE OF CREATININ BASED ON FIRST 48 HOURS IN THE ICU
  ,"MIN_CREAT_IN_ICU_48_HOURS" AS
  (SELECT "ICUD"."ICUSTAY_ID",
    MIN("CR"."VALUENUM") AS "MIN_CR_48"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME", 2) >  "CR"."CHARTTIME" 
  GROUP BY "ICUD"."ICUSTAY_ID"
  )
  --SELECT * FROM MIN_CREAT_IN_ICU_48_HOURS;
  
  -- THE MINIMUM VALUE OF CREATININ BASED ON THE ENTIRE HOSPITAL STAY 
  ,"MIN_CR_PER_HOSPITAL_STAY" AS
  ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MIN("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MIN_CR_PER_HOSP_ADM"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM "RRT"
    )
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )
  --SELECT * FROM MIN_CR_PER_HOSPITAL_STAY;
  -- THE MAXIMUM CREATININ BASED ON THE ENTIRE HOSPITAL STAY
  ,"MAX_CR_PER_HOSPITAL_STAY" AS
  ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MAX("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MAX_CR_PER_HOSP_ADM"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM "RRT"
    )
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )
  
  -- THE MINIUMUM CREATININ BASED ON FIRST 48 HOURS IN THE HOSPITAL
  -- WE USED THIS FOR OUR INTERVENTION GROUP...
  ,"MIN_CR_PER_HOSP_STAY_48" AS
  ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MIN("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MIN_CR_PER_HOSP_ADM_48"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM "RRT"
    )
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME", 2) >  "LE"."CHARTTIME"     
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )
  
 
  
  -- THE MAXIMUM VALUE OF CREATININ BASED ON THE FIRST 48 HOURS IN THE HOSPITAL
  ,"MAX_CR_PER_HOSP_STAY_48" AS
  ( SELECT DISTINCT "ICUD"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    MAX("LE"."VALUENUM") OVER ( PARTITION BY "ICUD"."SUBJECT_ID", "ICUD"."ICUSTAY_ID" ) AS "MAX_CR_PER_HOSP_ADM_48"
  FROM "MIMIC2V26"."labevents" "LE"
  JOIN "MIMIC2V26"."icustay_detail" "ICUD"
  ON ( "ICUD"."ICUSTAY_ID" = "LE"."ICUSTAY_ID" )
  WHERE "LE"."ITEMID"      = 50090
  AND "LE"."VALUENUM"     <> 0
    /* ELIMINATE ZERO VALUES TO PREVENT DIVIDE BY ZERO ERRORS LATER */
  AND "ICUD"."SUBJECT_ID" NOT IN
    ( SELECT "SUBJECT_ID" FROM "RRT"
    )
  AND ADD_DAYS("ICUD"."ICUSTAY_INTIME", 2) >  "LE"."CHARTTIME"   
    
    /* ELIMINATE PATIENTS WHO HAVE ACUTE RENAL FAILURE WITH DIALYSIS */
  )
  --SELECT * FROM MAX_CR_PER_HOSP_STAY_48;
  

-- THIS SECTION IS TO FIND WHERE THE CREATININ IS DECREASING --
-- SO THAT WE CAN FIND THE THEREPUTIC RANGE.
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
,TEST1 AS (
SELECT "ICUD"."ICUSTAY_ID",
       "CR"."VALUENUM",
       "CR"."CHARTTIME"
  FROM "MIMIC2V26"."labevents" "CR",
       "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "CR"."ITEMID"   = 50090
  AND "CR"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
  --AND ROWNUM < 100
  ORDER BY "ICUSTAY_ID", "CHARTTIME", "VALUENUM"
  )
--SELECT * FROM TEST1;

, "TEST2" AS(
SELECT "ICUSTAY_ID", 
       MAX("VALUENUM") AS "MAX_VAL" 
  FROM "TEST1"
  GROUP BY "ICUSTAY_ID"
)

,"TEST3" AS(
SELECT "T1"."ICUSTAY_ID",
       "T1"."CHARTTIME",
       "T1"."VALUENUM"
FROM "TEST1" "T1"
JOIN "TEST2" "T2"
ON "T1"."ICUSTAY_ID" = "T2"."ICUSTAY_ID"
WHERE "T2"."MAX_VAL" = "T1"."VALUENUM"
ORDER BY "ICUSTAY_ID","CHARTTIME"
)
--SELECT * FROM TEST3;

,"CR_MAX_TIMES" AS(
SELECT "ICUSTAY_ID",
       MAX("CHARTTIME") AS "CR_MAX_TIME"
FROM "TEST3"
GROUP BY "ICUSTAY_ID"
)
--SELECT * FROM CR_MAX_TIMES;

-- THIS IS THE TIME POINT WHERE AFTER THEY WILL 
--BECOME BETTER ACCORDING TO THE MEASUREMENTS.
,"CR_MAX_VAL_TIME" AS(
SELECT DISTINCT  
    "T3"."ICUSTAY_ID",
    "T3"."VALUENUM" AS "MAX_CR_VALUE",
    "CR"."CR_MAX_TIME",
    ROUND(SECONDS_BETWEEN("CR"."CR_MAX_TIME", "ICUD"."ICUSTAY_INTIME")/(60*60) ,2) AS "HR_BET_ICU_IN_AND_CR_MAX",
    ROUND(SECONDS_BETWEEN("CR"."CR_MAX_TIME", "ICUD"."ICUSTAY_INTIME")/(60*60) ,2) / ROUND(SECONDS_BETWEEN("ICUD"."ICUSTAY_OUTTIME", "ICUD"."ICUSTAY_INTIME")/(60*60),2) AS "PERC_OF_TIME_NOT_THERAPUTIC"
FROM "TEST3" "T3"
JOIN "CR_MAX_TIMES" "CR"
ON "CR"."ICUSTAY_ID" = "T3"."ICUSTAY_ID"
JOIN "MIMIC2V26"."icustay_detail" "ICUD"
ON "T3"."ICUSTAY_ID" = "ICUD"."ICUSTAY_ID"
WHERE "CR_MAX_TIME" = "CHARTTIME"
)
--SELECT * FROM CR_MAX_VAL_TIME;

,"FINAL_CREAT_TIMES" AS(
SELECT "ICUSTAY_ID",
       MAX("CHARTTIME") AS "FINAL_CREAT_TIME"
FROM "TEST1"
GROUP BY "ICUSTAY_ID"
)
--SELECT * FROM FINAL_CREAT_TIMES;


,"CR_FINAL_VALUES" AS(
SELECT DISTINCT  
    "T1"."ICUSTAY_ID",
    "T1"."VALUENUM" AS "FINAL_CR_VALUE",
    "FCT"."FINAL_CREAT_TIME"
FROM "TEST1" "T1"
JOIN "FINAL_CREAT_TIMES" "FCT"
ON "FCT"."ICUSTAY_ID" = "T1"."ICUSTAY_ID"
WHERE "FINAL_CREAT_TIME" = "CHARTTIME"
)

--SELECT * FROM CR_FINAL_VALUES;
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

,"CREAT_VALUES" AS
  ( SELECT DISTINCT "CR"."SUBJECT_ID",
    "ICUD"."ICUSTAY_ID",
    "ICUD"."ICUSTAY_AGE_GROUP" AS "HOSPITAL_AGE_GROUP",
    "ICUD"."ICUSTAY_ADMIT_AGE" AS "HOSPITAL_ADMIT_AGE",
    "ICUD"."ICUSTAY_INTIME",
    "ICUD"."ICUSTAY_OUTTIME",
    "CR"."CHARTTIME",
    TO_CHAR("CR"."CHARTTIME", 'DD MON, YYYY HH24:MI:SS')                                                                                                             AS "LONG_CHARTTIME",
    "CR"."VALUENUM"                                                                                                                                                  AS "CURRENT_CR",
    MAX("CR"."VALUENUM") OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME")                        AS "MAX_CR_NEXT_TWO_DAY",
    MAX("CR"."VALUENUM") OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME")    - "CR"."VALUENUM"       AS "MAX_INCREASE",
    (MAX("CR"."VALUENUM") OVER ( PARTITION BY "ICUD"."ICUSTAY_ID" ORDER BY "CR"."CHARTTIME") ) * 100 / "CR"."VALUENUM" AS "PERCENTAGE_INCREASE"
  FROM "MIMIC2V26"."labevents" "CR",
    "MIMIC2V26"."icustay_detail" "ICUD"
  WHERE "ICUD"."ICUSTAY_ID" = "CR"."ICUSTAY_ID"
  AND "CR"."ITEMID"         = 50090
  AND "CR"."VALUENUM"      <> 0
    /* ELIMINATE '0'S TO PREVENT DIVIDE BY ZERO ERROR */
  AND "CR"."VALUENUM" IS NOT NULL
  ORDER BY "CR"."SUBJECT_ID",
    "CR"."CHARTTIME"
  )
  --SELECT * FROM CREAT_VALUES;
  

  ,
  "MAX_CREAT_INCREASE" AS
  ( SELECT DISTINCT "CV"."SUBJECT_ID",
    "CV"."ICUSTAY_ID",
    "CV"."HOSPITAL_AGE_GROUP",
    "CV"."HOSPITAL_ADMIT_AGE",
    MAX("CV"."MAX_INCREASE") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR")                                                 "MAX_INCREASE",
    FIRST_VALUE("CV"."LONG_CHARTTIME") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR" ORDER BY "CV"."MAX_INCREASE" DESC)         "DATE_MAX_INCREASE",
    MAX("CV"."PERCENTAGE_INCREASE") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR")                                          "MAX_PERCENT_INCREASE",
    FIRST_VALUE("CV"."LONG_CHARTTIME") OVER (PARTITION BY "CV"."SUBJECT_ID", "CV"."ICUSTAY_ID", "CV"."HOSPITAL_AGE_GROUP", "CV"."HOSPITAL_ADMIT_AGE", "MAX_CR", "FIRST_CR" ORDER BY "CV"."PERCENTAGE_INCREASE" DESC)  "DATE_MAX_PERCENT_INCREASE",
    
    "FCR"."FIRST_CR",
    
    "CR"."MAX_CR" AS    "MAX_CR_PER_ICUSTAY",
    "MICR"."MIN_CR" AS  "MIN_CR_PER_ICUSTAY",

    "MCPHS"."MIN_CR_PER_HOSP_ADM",
    "MACPHS"."MAX_CR_PER_HOSP_ADM",
    
    -- THE 48 HR VALUES
    "MCIHR"."MAX_CR_48" AS        "MAX_CR_ICU_48HRS",
    "MICI48"."MIN_CR_48" AS       "MIN_CR_ICU_48HRS",
    
    "MICRHS"."MIN_CR_PER_HOSP_ADM_48",
    "MACRHS"."MAX_CR_PER_HOSP_ADM_48",
    
    
    --MAX CREATININ INCREASE (AND %) PER ICUSTAY
    --("CR"."MAX_CR" - "MICR"."MIN_CR")                                                               AS MAX_CR_INCREASE_ICUSTAY,
    --("CR"."MAX_CR" - "MICR"."MIN_CR")/"MICR"."MIN_CR"                                                   AS MAX_CR_INCREASE_ICU_PERC,
    
    --MAX CREATININ INCREASE (AND %) PER HOSPITAL STAY
    --("MACPHS"."MAX_CR_PER_HOSP_ADM" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                AS MAX_CR_INCREASE_PER_HOSSTAY,
    --("MACPHS"."MAX_CR_PER_HOSP_ADM" - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"    AS MAX_CR_INCREASE_PER_HOS_PERC,
    
    --MAX CREATININ INCREASE USING MAX ICU VERSUS MIN IN HOSPITAL
    --("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                                 AS MAX_CR_INCR_ICU_MAX_HOS_MIN,
    --("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM")/"MCPHS"."MIN_CR_PER_HOSP_ADM"                       AS MAX_CR_INCR_ICU_MAX_HOS_MIN_PERC,
    
    
    --MAX CREATININ INCREASE IN ICU FOR ONLY FIRST 48 HOURS
    ("MCIHR"."MAX_CR_48" - "MICI48"."MIN_CR_48")                                                    AS "MAX_CR_INCREASE_ICU_48",
    100*("MCIHR"."MAX_CR_48" - "MICI48"."MIN_CR_48") / "MICI48"."MIN_CR_48"                                 AS "MAX_CR_INCR_ICU_48_PERC",
    
    --MAX CREATININ INCREASE IN FIRST 48 HOURS ICU VERSUS MIN OF HOSPITAL STAY
    ("MCIHR"."MAX_CR_48" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                           AS "MAX_CR_INCR_ICU_48_VS_HOS",
    100*("MCIHR"."MAX_CR_48" - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"               AS "MAX_CR_INCR_ICU_48_VS_HOS_PERC",
    
    -- MAX CREATININ INCREASE IN TOTAL ICU STAY VERSUS MIN IN THE HOSPITAL                  
    ("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                                 AS "MAX_CR_INCR_ICU_VS_HOS",          
    100*("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"                     AS "MAX_CR_INCR_ICU_VS_HOS_PERC",      
    
    
    "FCR"."FIRST_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM" AS       "BL_CR_INCREASE",           -- DIFFERENCE BETWEEN CR ADMISSION AND MINIMUM VALUE OVER HOSPITAL STAY 
    "FCR"."FIRST_CR" * 100 / "MCPHS"."MIN_CR_PER_HOSP_ADM" AS "BL_CR_PERCENT_INCREASE"    -- % VALUE OF ABOVE
  FROM "CREAT_VALUES" "CV"
  
  JOIN "MAX_CREATININE_PER_ICU_STAY"            "CR"
  ON ( "CV"."ICUSTAY_ID" = "CR"."ICUSTAY_ID" )
  JOIN "MIN_CREATININE_PER_ICU_STAY"            "MICR"
  ON ( "CV"."ICUSTAY_ID" = "MICR"."ICUSTAY_ID")
  
  JOIN "FIRST_CREATININE_PER_ICU_STAY"          "FCR"
  ON ( "CV"."ICUSTAY_ID" = "FCR"."ICUSTAY_ID" )
  
  
  LEFT JOIN "MIN_CR_PER_HOSPITAL_STAY"          "MCPHS"
  ON ( "CV"."ICUSTAY_ID" = "MCPHS"."ICUSTAY_ID" )
  
  --THE 48 HOUR PART
  LEFT JOIN "MAX_CR_PER_HOSPITAL_STAY"          "MACPHS"
  ON ( "CV"."ICUSTAY_ID" = "MACPHS"."ICUSTAY_ID" ) 
  
  JOIN "MAX_CREAT_IN_ICU_48_HOURS"              "MCIHR"
  ON ( "CV"."ICUSTAY_ID" = "MCIHR"."ICUSTAY_ID") 
  JOIN "MIN_CREAT_IN_ICU_48_HOURS"              "MICI48"
  ON ( "CV"."ICUSTAY_ID" = "MICI48"."ICUSTAY_ID" ) 
  
  JOIN "MIN_CR_PER_HOSP_STAY_48"                "MICRHS"
  ON ( "CV"."ICUSTAY_ID" = "MICRHS"."ICUSTAY_ID" ) 
  JOIN "MAX_CR_PER_HOSP_STAY_48"                "MACRHS"
  ON ( "CV"."ICUSTAY_ID" = "MACRHS"."ICUSTAY_ID" ) 
  
  WHERE "MICR"."MIN_CR" > 0
  AND "MCPHS"."MIN_CR_PER_HOSP_ADM" > 0
  AND "MICI48"."MIN_CR_48" > 0
  AND "MICRHS"."MIN_CR_PER_HOSP_ADM_48" > 0
  
  )
  --SELECT * FROM MAX_CREAT_INCREASE;
  
  
  ,
  "CR_AKI_FLAG" AS
  (SELECT "SUBJECT_ID",
    "ICUSTAY_ID",
    "HOSPITAL_ADMIT_AGE",
    "HOSPITAL_AGE_GROUP",
    "FIRST_CR",
    "MAX_CR_PER_ICUSTAY",
    "MAX_INCREASE",
    "MAX_PERCENT_INCREASE",
  
    -- IN THE FIRST 48 HOURS OF ICU
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND (("MAX_CR_INCREASE_ICU_48"     >= 0.3
       AND   "MAX_CR_INCR_ICU_48_PERC"    < 200 )
      OR  (  "MAX_CR_INCR_ICU_48_PERC"    >= 150
      AND    "MAX_CR_INCR_ICU_48_PERC"    < 200) ) )
      THEN 1
      ELSE 0
    END AS "AKI1_ICU48",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND   "MAX_CR_INCR_ICU_48_PERC"    < 300
       AND   "MAX_CR_INCR_ICU_48_PERC"    >= 200 )
      THEN 1
      ELSE 0
    END AS "AKI2_ICU48",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           >= 4
      OR "MAX_CR_INCR_ICU_48_PERC" >= 300 )
      THEN 1
      ELSE 0
    END AS "AKI3_ICU48",
   
   
    -- MAX CR IN 48 HRS OF ICU VS MIN IN HOSPITAL STAY
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND (("MAX_CR_INCR_ICU_48_VS_HOS"     >= 0.3
       AND   "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    < 200 )
      OR  (  "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    >= 150
      AND    "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    < 200) ) )
      THEN 1
      ELSE 0
    END AS "AKI1_ICU48_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           < 4
       AND   "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    < 300
       AND   "MAX_CR_INCR_ICU_48_VS_HOS_PERC"    >= 200 )
      THEN 1
      ELSE 0
    END AS "AKI2_ICU48_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_ICU_48HRS"           >= 4
      OR "MAX_CR_INCR_ICU_48_VS_HOS_PERC" >= 300 )
      THEN 1
      ELSE 0
    END AS "AKI3_ICU48_VS_HOSP", 
    
    
    --MAX CREATININ INCREASE IN ICU FOR ONLY FIRST 48 HOURS
    --("MCIHR"."MAX_CR_"48 - MICI48.MIN_CR_48)                                                    AS MAX_CR_INCREASE_ICU_48,
    --100*("MCIHR"."MAX_CR_"48 - MICI48.MIN_CR_48) / MICI48.MIN_CR_48                                 AS MAX_CR_INCR_ICU_48_PERC,
    
    --MAX CREATININ INCREASE IN FIRST 48 HOURS ICU VERSUS MIN OF HOSPITAL STAY
    --("MCIHR"."MAX_CR_"48 - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                           AS MAX_CR_INCR_ICU_48_VS_HOS,
    --100*("MCIHR"."MAX_CR_"48 - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"               AS MAX_CR_INCR_ICU_48_VS_HOS_PERC,
    
    -- MAX CREATININ INCREASE IN TOTAL ICU STAY VERSUS MIN IN THE HOSPITAL                  
    --("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM")                                                 AS MAX_CR_INCR_ICU_VS_HOS,          
    --100*("CR"."MAX_CR" - "MCPHS"."MIN_CR_PER_HOSP_ADM") / "MCPHS"."MIN_CR_PER_HOSP_ADM"                     AS MAX_CR_INCR_ICU_VS_HOS_PERC,  
    
    -- MAX CR IN ICU, VERSUS HOSPITAL MIN
    CASE
      WHEN ( "MAX_CR_PER_ICUSTAY"           < 4
       AND (("MAX_CR_INCR_ICU_VS_HOS"     >= 0.3
       AND   "MAX_CR_INCR_ICU_VS_HOS_PERC"    < 200 )
      OR  (  "MAX_CR_INCR_ICU_VS_HOS_PERC"    >= 150
      AND    "MAX_CR_INCR_ICU_VS_HOS_PERC"    < 200) ) )
      THEN 1
      ELSE 0
    END AS "AKI1_ICU_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_PER_ICUSTAY"           < 4
       AND   "MAX_CR_INCR_ICU_VS_HOS_PERC"    < 300
       AND   "MAX_CR_INCR_ICU_VS_HOS_PERC"    >= 200 )
      THEN 1
      ELSE 0
    END AS "AKI2_ICU_VS_HOSP",
    
    CASE
      WHEN ( "MAX_CR_PER_ICUSTAY"           >= 4
      OR "MAX_CR_INCR_ICU_VS_HOS_PERC" >= 300 )
      THEN 1
      ELSE 0
    END AS "AKI3_ICU_VS_HOSP"
      
    
   /* CASE
      WHEN ( MAX_CR_PER_ICUSTAY  < 4
      AND ( ( MAX_INCREASE      >= 0.3
      AND MAX_PERCENT_INCREASE   < 200 )
      OR ( MAX_PERCENT_INCREASE >= 150
      AND MAX_PERCENT_INCREASE   < 200 ) ) )
      THEN 1
      ELSE 0
    END AS AKI1,
    CASE
      WHEN ( ( BL_CR_INCREASE     >= 0.3
      AND BL_CR_PERCENT_INCREASE   < 200 )
      OR ( BL_CR_PERCENT_INCREASE >= 150
      AND BL_CR_PERCENT_INCREASE   < 200 ) )
      THEN 1
      ELSE 0
    END AS AKI1_BL,
    CASE
      WHEN ( MAX_CR_PER_ICUSTAY               < 4
      AND ( MAX_PERCENT_INCREASE >= 200
      AND MAX_PERCENT_INCREASE    < 300 ) )
      THEN 1
      ELSE 0
    END AS AKI2,
    CASE
      WHEN ( ( BL_CR_PERCENT_INCREASE >= 200
      AND BL_CR_PERCENT_INCREASE       < 300 ) )
      THEN 1
      ELSE 0
    END AS AKI2_BL,
    CASE
      WHEN ( MAX_CR_PER_ICUSTAY           >= 4
      OR MAX_PERCENT_INCREASE >= 300 )
      THEN 1
      ELSE 0
    END AS AKI3,
    CASE
      WHEN ( BL_CR_PERCENT_INCREASE >= 300 )
      THEN 1
      ELSE 0
    END AS AKI3_BL,
    CASE
      WHEN ( MAX_CR_PER_ICUSTAY            < 4
      AND ( MAX_INCREASE       < 0.3
      AND MAX_PERCENT_INCREASE < 150 ) )
      THEN 1
      ELSE 0
    END AS NO_AKI,
    CASE
      WHEN ( ( BL_CR_INCREASE    < 0.3
      AND BL_CR_PERCENT_INCREASE < 150 ) )
      THEN 1
      ELSE 0
    END AS NO_AKI_BL */
  FROM "MAX_CREAT_INCREASE"
  ) 
  
  --SELECT COUNT(*) FROM CR_AKI_FLAG;
  --THOSE THAT HAVE AKI ACCORDING TO CR 27592
  ,
  "CR_AKI_PATIENTS" AS
  (SELECT "CAF"."ICUSTAY_ID",
    "CAF"."SUBJECT_ID",
    CASE
      WHEN ( "CAF"."AKI1_ICU48" = 1)
      THEN 1
      WHEN ( "CAF"."AKI2_ICU48" =1)
      THEN 2
      WHEN ( "CAF"."AKI3_ICU48" =1)
      THEN 3
      ELSE 0
    END AS "AKI_CATEGORY_ICU48",
    
    CASE
      WHEN ( "CAF"."AKI1_ICU48_VS_HOSP" = 1)
      THEN 1
      WHEN ( "CAF"."AKI2_ICU48_VS_HOSP" =1)
      THEN 2
      WHEN ( "CAF"."AKI3_ICU48_VS_HOSP" =1)
      THEN 3
      ELSE 0
    END AS "AKI_CATEGORY_ICU48_VS_HOSP",
    
    CASE
      WHEN ( "CAF"."AKI1_ICU_VS_HOSP" = 1)
      THEN 1
      WHEN ( "CAF"."AKI2_ICU_VS_HOSP" = 1)
      THEN 2
      WHEN ( "CAF"."AKI3_ICU_VS_HOSP" = 1)
      THEN 3
      ELSE 0
    END AS "AKI_CATEGORY_ICU_VS_HOSP"
    
  FROM "CR_AKI_FLAG" "CAF"
  )

SELECT * FROM "CR_AKI_PATIENTS";


