select * from AFL_FUNCTIONS where AREA_NAME = 'DTW_AREA';


DROP TYPE TYPE_IN_1;
CREATE TYPE TYPE_IN_1 AS TABLE ("AMPLITUDE" INT);

DROP TYPE TYPE_IN_2;
CREATE TYPE TYPE_IN_2 AS TABLE ("distance_type" varchar(255), "windows_size" int);

DROP TYPE TYPE_OUT_1;
CREATE TYPE TYPE_OUT_1 AS TABLE ("similarity" double);

DROP TYPE TYPE_OUT_2;
CREATE TYPE TYPE_OUT_2 AS TABLE ("x" int, "y" int);

DROP TABLE SIGNATURE;
CREATE COLUMN TABLE SIGNATURE ("ID" INT, "TYPENAME" VARCHAR(100), "DIRECTION" VARCHAR(100));
INSERT INTO SIGNATURE VALUES (1, 'JUHUA.TYPE_IN_1', 'in');
INSERT INTO SIGNATURE VALUES (2, 'JUHUA.TYPE_IN_1', 'in');
INSERT INTO SIGNATURE VALUES (3, 'JUHUA.TYPE_IN_2', 'in');
INSERT INTO SIGNATURE VALUES (4, 'JUHUA.TYPE_OUT_1', 'out');
INSERT INTO SIGNATURE VALUES (5, 'JUHUA.TYPE_OUT_2', 'out');

CALL SYSTEM.AFL_WRAPPER_ERASER('TEST_DTW');
CALL SYSTEM.AFL_WRAPPER_GENERATOR('TEST_DTW', 'DTW_AREA', 'DTW', SIGNATURE);


DROP TABLE T_I_1;
CREATE COLUMN TABLE T_I_1 LIKE TYPE_IN_1;
INSERT INTO T_I_1 VALUES (1);
INSERT INTO T_I_1 VALUES (1);
INSERT INTO T_I_1 VALUES (1);
INSERT INTO T_I_1 VALUES (1);
INSERT INTO T_I_1 VALUES (1);
INSERT INTO T_I_1 VALUES (1);

DROP TABLE T_I_2;
CREATE COLUMN TABLE T_I_2 LIKE TYPE_IN_1;
INSERT INTO T_I_2 VALUES (0);
INSERT INTO T_I_2 VALUES (0);
INSERT INTO T_I_2 VALUES (0);
INSERT INTO T_I_2 VALUES (0);
INSERT INTO T_I_2 VALUES (0);
INSERT INTO T_I_2 VALUES (0);

DROP TABLE T_I_3;
CREATE COLUMN TABLE T_I_3 LIKE TYPE_IN_2;
INSERT INTO T_I_3 VALUES ('euclidean',2000);

DROP TABLE T_O_1;
CREATE COLUMN TABLE T_O_1 LIKE TYPE_OUT_1;

DROP TABLE T_O_2;
CREATE COLUMN TABLE T_O_2 LIKE TYPE_OUT_2;

CALL _SYS_AFL.TEST_DTW(T_I_1, T_I_2, T_I_3, T_O_1, T_O_2) WITH OVERVIEW;
SELECT * FROM T_O_1;
SELECT * FROM T_O_2;
