-- Execute as administrative user (e.g. SYSTEM).

select * from AFL_FUNCTIONS where AREA_NAME = 'MIMICSIGNAL_AREA';

-- Grant execution privileges to test user


-- DEMONSTRATE_FLEXIBLE_COLUMNS (make sure the wrapper generator procedure is created first)
DROP TYPE TYPE_IN;
--CREATE TYPE TYPE_IN AS TABLE ("SAMPLE_ID" BIGINT,"AMPLITUDE" INTEGER);
CREATE TYPE TYPE_IN AS TABLE ("SAMPLE_ID" INT,"AMPLITUDE" int);

DROP TYPE TYPE_OUT;
CREATE TYPE TYPE_OUT AS TABLE ("Heart_Beat" INT);
DROP TABLE SIGNATURE;
CREATE COLUMN TABLE SIGNATURE ("ID" INT, "TYPENAME" VARCHAR(100), "DIRECTION" VARCHAR(100));
INSERT INTO SIGNATURE VALUES (1, 'JUHUA.TYPE_IN', 'in');
INSERT INTO SIGNATURE VALUES (2, 'JUHUA.TYPE_OUT', 'out');
CALL SYSTEM.AFL_WRAPPER_ERASER('ABP_TEST');
CALL SYSTEM.AFL_WRAPPER_GENERATOR('ABP_TEST', 'MIMICSIGNAL_AREA', 'HEARTBEATDETECTION', SIGNATURE);



DROP VIEW ABP_TEST_VIEW;
create view ABP_TEST_VIEW as 
(select SAMPLE_ID, AMPLITUDE 
from "MIMIC2V26"."wav_sig_ABP"
where "MIMIC2V26"."wav_sig_ABP"."RECORD_ID" =2   
and SAMPLE_ID > 14430740 
AND SAMPLE_ID < 14439740 ORDER BY "SAMPLE_ID");


drop table HEART_BEAT;
create table HEART_BEAT LIKE TYPE_OUT;



call _SYS_AFL.ABP_TEST (ABP_TEST_VIEW, HEART_BEAT) with OVERVIEW;
select * from HEART_BEAT;
