-- Clinical Data Clustering by K-Means (Tier 1)
-- With six additional variables, representing Admission Medications
-- (as extracted from the notes of Discharge Summaries)

-- Created by: Ishrar Hussain
-- Date: March 5, 2015

DROP TYPE PAL_KMEANS_DATA_T;
CREATE TYPE PAL_KMEANS_DATA_T AS TABLE(
	"ID" INTEGER, 
	"AGE" DOUBLE,
	"GENDER_MALE" DOUBLE,
	"SAPSI_FIRST" DOUBLE,
	"SOFA_FIRST" DOUBLE,
	"ELIX_HOSPITAL_MORT_PT" DOUBLE,
	"MICU_FLG" DOUBLE,
	"SICU_FLG" DOUBLE,
	"CCU_FLG" DOUBLE,
	"CSRU_FLG" DOUBLE,
	"DAY_ICU_INTIME_NUM" DOUBLE,
	"HOUR_ICU_INTIME" DOUBLE,
	"CONGESTIVE_HEART_FAILURE" DOUBLE,
	"CARDIAC_ARRHYTHMIAS" DOUBLE,
	"VALVULAR_DISEASE" DOUBLE,
	"PULMONARY_CIRCULATION" DOUBLE,
	"PERIPHERAL_VASCULAR" DOUBLE,
	"HYPERTENSION" DOUBLE,
	"PARALYSIS" DOUBLE,
	"OTHER_NEUROLOGICAL" DOUBLE,
	"CHRONIC_PULMONARY" DOUBLE,
	"DIABETES_UNCOMPLICATED" DOUBLE,
	"DIABETES_COMPLICATED" DOUBLE,
	"HYPOTHYROIDISM" DOUBLE,
	"RENAL_FAILURE" DOUBLE,
	"LIVER_DISEASE" DOUBLE,
	"PEPTIC_ULCER" DOUBLE,
	"AIDS" DOUBLE,
	"LYMPHOMA" DOUBLE,
	"METASTATIC_CANCER" DOUBLE,
	"SOLID_TUMOR" DOUBLE,
	"RHEUMATOID_ARTHRITIS" DOUBLE,
	"COAGULOPATHY" DOUBLE,
	"OBESITY" DOUBLE,
	"WEIGHT_LOSS" DOUBLE,
	"FLUID_ELECTROLYTE" DOUBLE,
	"BLOOD_LOSS_ANEMIA" DOUBLE,
	"DEFICIENCY_ANEMIAS" DOUBLE,
	"ALCOHOL_ABUSE" DOUBLE,
	"DRUG_ABUSE" DOUBLE,
	"PSYCHOSES" DOUBLE,
	"DEPRESSION" DOUBLE,
	"HOSP_EXP_FLG" DOUBLE,
	"ICU_EXP_FLG" DOUBLE,
	"SURVIVAL_DAY" DOUBLE,
	"ICU_LOS_DAY" DOUBLE,
	"HOSPITAL_LOS_DAY" DOUBLE,
	"NOTES_DIABETICMEDICATION" DOUBLE,
	"NOTES_BETABLOCKER" DOUBLE,
	"NOTES_DIURECTICS" DOUBLE,
	"NOTES_ACEINHIBITOR" DOUBLE,
	"NOTES_CALCIUMCHANNELBLOCKER" DOUBLE,
	"NOTES_ARB" DOUBLE
);

DROP TYPE PAL_CONTROL_T;
CREATE TYPE PAL_CONTROL_T AS TABLE( 
	"NAME" VARCHAR (100), 
	"INTARGS" INTEGER, 
	"DOUBLEARGS" DOUBLE, 
	"STRINGARGS" VARCHAR (100)
);

DROP TYPE PAL_KMEANS_ASSIGNED_T;
CREATE TYPE PAL_KMEANS_ASSIGNED_T AS TABLE(
	"ID" INTEGER,
	"CLUSTER" INTEGER,
	"DISTANCE" DOUBLE,
	"SLIGHT_SILHOUETTE" DOUBLE
);

DROP TYPE PAL_KMEANS_CENTERS_T;
CREATE TYPE PAL_KMEANS_CENTERS_T AS TABLE(
	"CLUSTER_ID" INTEGER,
	"AGE" DOUBLE,
	"GENDER_MALE" DOUBLE,
	"SAPSI_FIRST" DOUBLE,
	"SOFA_FIRST" DOUBLE,
	"ELIX_HOSPITAL_MORT_PT" DOUBLE,
	"MICU_FLG" DOUBLE,
	"SICU_FLG" DOUBLE,
	"CCU_FLG" DOUBLE,
	"CSRU_FLG" DOUBLE,
	"DAY_ICU_INTIME_NUM" DOUBLE,
	"HOUR_ICU_INTIME" DOUBLE,
	"CONGESTIVE_HEART_FAILURE" DOUBLE,
	"CARDIAC_ARRHYTHMIAS" DOUBLE,
	"VALVULAR_DISEASE" DOUBLE,
	"PULMONARY_CIRCULATION" DOUBLE,
	"PERIPHERAL_VASCULAR" DOUBLE,
	"HYPERTENSION" DOUBLE,
	"PARALYSIS" DOUBLE,
	"OTHER_NEUROLOGICAL" DOUBLE,
	"CHRONIC_PULMONARY" DOUBLE,
	"DIABETES_UNCOMPLICATED" DOUBLE,
	"DIABETES_COMPLICATED" DOUBLE,
	"HYPOTHYROIDISM" DOUBLE,
	"RENAL_FAILURE" DOUBLE,
	"LIVER_DISEASE" DOUBLE,
	"PEPTIC_ULCER" DOUBLE,
	"AIDS" DOUBLE,
	"LYMPHOMA" DOUBLE,
	"METASTATIC_CANCER" DOUBLE,
	"SOLID_TUMOR" DOUBLE,
	"RHEUMATOID_ARTHRITIS" DOUBLE,
	"COAGULOPATHY" DOUBLE,
	"OBESITY" DOUBLE,
	"WEIGHT_LOSS" DOUBLE,
	"FLUID_ELECTROLYTE" DOUBLE,
	"BLOOD_LOSS_ANEMIA" DOUBLE,
	"DEFICIENCY_ANEMIAS" DOUBLE,
	"ALCOHOL_ABUSE" DOUBLE,
	"DRUG_ABUSE" DOUBLE,
	"PSYCHOSES" DOUBLE,
	"DEPRESSION" DOUBLE,
	"HOSP_EXP_FLG" DOUBLE,
	"ICU_EXP_FLG" DOUBLE,
	"SURVIVAL_DAY" DOUBLE,
	"ICU_LOS_DAY" DOUBLE,
	"HOSPITAL_LOS_DAY" DOUBLE,
	"NOTES_DIABETICMEDICATION" DOUBLE,
	"NOTES_BETABLOCKER" DOUBLE,
	"NOTES_DIURECTICS" DOUBLE,
	"NOTES_ACEINHIBITOR" DOUBLE,
	"NOTES_CALCIUMCHANNELBLOCKER" DOUBLE,
	"NOTES_ARB" DOUBLE
);

DROP TYPE PAL_KMEANS_SIL_CENTERS_T;
CREATE TYPE PAL_KMEANS_SIL_CENTERS_T AS TABLE(
	"CLUSTER_ID" INTEGER,
	"SLIGHT_SILHOUETTE" DOUBLE
);

DROP TYPE PAL_KMEANS_STATISTIC_T;
CREATE TYPE PAL_KMEANS_STATISTIC_T AS TABLE(
	"NAME" VARCHAR(50),
	"VALUE" DOUBLE
);

DROP TABLE PAL_KMEANS_PDATA_TBL;
CREATE COLUMN TABLE PAL_KMEANS_PDATA_TBL("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (1, CURRENT_SCHEMA, 'PAL_KMEANS_DATA_T', 'IN'); 
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (2, CURRENT_SCHEMA, 'PAL_CONTROL_T', 'IN'); 
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (3, CURRENT_SCHEMA, 'PAL_KMEANS_ASSIGNED_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (4, CURRENT_SCHEMA, 'PAL_KMEANS_CENTERS_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (5, CURRENT_SCHEMA, 'PAL_KMEANS_SIL_CENTERS_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (6, CURRENT_SCHEMA, 'PAL_KMEANS_STATISTIC_T', 'OUT'); 


CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_DROP(CURRENT_SCHEMA, 'PAL_KMEANS_PROC');

CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'KMEANS', CURRENT_SCHEMA, 'PAL_KMEANS_PROC', PAL_KMEANS_PDATA_TBL);


DROP TABLE PAL_CONTROL_TBL;
CREATE COLUMN TABLE PAL_CONTROL_TBL(
	"NAME" VARCHAR (100), 
	"INTARGS" INTEGER, 
	"DOUBLEARGS" DOUBLE, 
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 1, null, null);
INSERT INTO PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);

DROP TABLE PAL_KMEANS_ASSIGNED_TBL;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL LIKE PAL_KMEANS_ASSIGNED_T;

DROP TABLE PAL_KMEANS_CENTERS_TBL;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL LIKE PAL_KMEANS_CENTERS_T;

DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL LIKE PAL_KMEANS_SIL_CENTERS_T;

DROP TABLE PAL_KMEANS_STATISTIC_TBL;
CREATE COLUMN TABLE PAL_KMEANS_STATISTIC_TBL LIKE PAL_KMEANS_STATISTIC_T;
		
DROP PROCEDURE PAL_KMEANS_TIER1;

CREATE PROCEDURE PAL_KMEANS_TIER1 () 
	LANGUAGE SQLSCRIPT AS
BEGIN
	DECLARE cluster_count INT := 1;
	DECLARE iteration_count INT := 0;
	DECLARE old_silhouette DOUBLE := 0;
	DECLARE new_silhouette DOUBLE := 0;

	WHILE :old_silhouette <= :new_silhouette DO
		old_silhouette := :new_silhouette ;
		
		EXECUTE IMMEDIATE 'DELETE FROM "PAL_KMEANS_ASSIGNED_TBL"';
		EXECUTE IMMEDIATE 'DELETE FROM "PAL_KMEANS_CENTERS_TBL"';
		EXECUTE IMMEDIATE 'DELETE FROM "PAL_KMEANS_SIL_CENTERS_TBL"';
		EXECUTE IMMEDIATE 'DELETE FROM "PAL_KMEANS_STATISTIC_TBL"';
		
		cluster_count := :cluster_count + 1;
		
		EXECUTE IMMEDIATE 'UPDATE PAL_CONTROL_TBL SET "INTARGS" = ' || :cluster_count || ' WHERE "NAME" = ''GROUP_NUMBER''';
		
		EXECUTE IMMEDIATE 'COMMIT';
		
		EXECUTE IMMEDIATE 'CALL PAL_KMEANS_PROC(PAL_CLSTR_TIER1_DATA_TBL, PAL_CONTROL_TBL, PAL_KMEANS_ASSIGNED_TBL, PAL_KMEANS_CENTERS_TBL, PAL_KMEANS_SIL_CENTERS_TBL, PAL_KMEANS_STATISTIC_TBL) with OVERVIEW';

		EXECUTE IMMEDIATE 'COMMIT';
		
		SELECT "VALUE" INTO new_silhouette FROM "PAL_KMEANS_STATISTIC_TBL" WHERE "NAME" = 'SlightSilhouette';
		
	END WHILE;
END;

CALL PAL_KMEANS_TIER1();

SELECT * FROM PAL_KMEANS_ASSIGNED_TBL;
SELECT * FROM PAL_KMEANS_CENTERS_TBL;
SELECT * FROM PAL_KMEANS_SIL_CENTERS_TBL;
SELECT * FROM PAL_KMEANS_STATISTIC_TBL;
